name: Super Linter Workflow
# This workflow runs the Super Linter to check code quality and style.
# It validates C and Python code, ensuring adherence to coding standards.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          VALIDATE_C: true
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Skip every file whose path contains "/unity/"
          FILTER_REGEX_EXCLUDE: '^.*/Unity/.*$'
          # ▶ tell clang-format to honour .clang-format ◀
          CLANG_FORMAT_STYLE: file